<?php
/**
 * V1HorizontalPodAutoscalerStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1HorizontalPodAutoscalerStatus Class Doc Comment
 *
 * @category Class
 * @description current status of a horizontal pod autoscaler
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1HorizontalPodAutoscalerStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.HorizontalPodAutoscalerStatus';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'current_cpu_utilization_percentage' => 'int',
        'current_replicas' => 'int',
        'desired_replicas' => 'int',
        'last_scale_time' => '\DateTime',
        'observed_generation' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'current_cpu_utilization_percentage' => 'int32',
        'current_replicas' => 'int32',
        'desired_replicas' => 'int32',
        'last_scale_time' => 'date-time',
        'observed_generation' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'current_cpu_utilization_percentage' => false,
        'current_replicas' => false,
        'desired_replicas' => false,
        'last_scale_time' => false,
        'observed_generation' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_cpu_utilization_percentage' => 'currentCPUUtilizationPercentage',
        'current_replicas' => 'currentReplicas',
        'desired_replicas' => 'desiredReplicas',
        'last_scale_time' => 'lastScaleTime',
        'observed_generation' => 'observedGeneration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_cpu_utilization_percentage' => 'setCurrentCpuUtilizationPercentage',
        'current_replicas' => 'setCurrentReplicas',
        'desired_replicas' => 'setDesiredReplicas',
        'last_scale_time' => 'setLastScaleTime',
        'observed_generation' => 'setObservedGeneration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_cpu_utilization_percentage' => 'getCurrentCpuUtilizationPercentage',
        'current_replicas' => 'getCurrentReplicas',
        'desired_replicas' => 'getDesiredReplicas',
        'last_scale_time' => 'getLastScaleTime',
        'observed_generation' => 'getObservedGeneration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('current_cpu_utilization_percentage', $data ?? [], null);
        $this->setIfExists('current_replicas', $data ?? [], null);
        $this->setIfExists('desired_replicas', $data ?? [], null);
        $this->setIfExists('last_scale_time', $data ?? [], null);
        $this->setIfExists('observed_generation', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['current_replicas'] === null) {
            $invalidProperties[] = "'current_replicas' can't be null";
        }
        if ($this->container['desired_replicas'] === null) {
            $invalidProperties[] = "'desired_replicas' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_cpu_utilization_percentage
     *
     * @return int|null
     */
    public function getCurrentCpuUtilizationPercentage()
    {
        return $this->container['current_cpu_utilization_percentage'];
    }

    /**
     * Sets current_cpu_utilization_percentage
     *
     * @param int|null $current_cpu_utilization_percentage currentCPUUtilizationPercentage is the current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.
     *
     * @return self
     */
    public function setCurrentCpuUtilizationPercentage($current_cpu_utilization_percentage)
    {
        if (is_null($current_cpu_utilization_percentage)) {
            throw new \InvalidArgumentException('non-nullable current_cpu_utilization_percentage cannot be null');
        }
        $this->container['current_cpu_utilization_percentage'] = $current_cpu_utilization_percentage;

        return $this;
    }

    /**
     * Gets current_replicas
     *
     * @return int
     */
    public function getCurrentReplicas()
    {
        return $this->container['current_replicas'];
    }

    /**
     * Sets current_replicas
     *
     * @param int $current_replicas currentReplicas is the current number of replicas of pods managed by this autoscaler.
     *
     * @return self
     */
    public function setCurrentReplicas($current_replicas)
    {
        if (is_null($current_replicas)) {
            throw new \InvalidArgumentException('non-nullable current_replicas cannot be null');
        }
        $this->container['current_replicas'] = $current_replicas;

        return $this;
    }

    /**
     * Gets desired_replicas
     *
     * @return int
     */
    public function getDesiredReplicas()
    {
        return $this->container['desired_replicas'];
    }

    /**
     * Sets desired_replicas
     *
     * @param int $desired_replicas desiredReplicas is the  desired number of replicas of pods managed by this autoscaler.
     *
     * @return self
     */
    public function setDesiredReplicas($desired_replicas)
    {
        if (is_null($desired_replicas)) {
            throw new \InvalidArgumentException('non-nullable desired_replicas cannot be null');
        }
        $this->container['desired_replicas'] = $desired_replicas;

        return $this;
    }

    /**
     * Gets last_scale_time
     *
     * @return \DateTime|null
     */
    public function getLastScaleTime()
    {
        return $this->container['last_scale_time'];
    }

    /**
     * Sets last_scale_time
     *
     * @param \DateTime|null $last_scale_time lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.
     *
     * @return self
     */
    public function setLastScaleTime($last_scale_time)
    {
        if (is_null($last_scale_time)) {
            throw new \InvalidArgumentException('non-nullable last_scale_time cannot be null');
        }
        $this->container['last_scale_time'] = $last_scale_time;

        return $this;
    }

    /**
     * Gets observed_generation
     *
     * @return int|null
     */
    public function getObservedGeneration()
    {
        return $this->container['observed_generation'];
    }

    /**
     * Sets observed_generation
     *
     * @param int|null $observed_generation observedGeneration is the most recent generation observed by this autoscaler.
     *
     * @return self
     */
    public function setObservedGeneration($observed_generation)
    {
        if (is_null($observed_generation)) {
            throw new \InvalidArgumentException('non-nullable observed_generation cannot be null');
        }
        $this->container['observed_generation'] = $observed_generation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


