<?php
/**
 * V1JobSpec
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1JobSpec Class Doc Comment
 *
 * @category Class
 * @description JobSpec describes how the job execution will look like.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1JobSpec implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.JobSpec';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'active_deadline_seconds' => 'int',
        'backoff_limit' => 'int',
        'backoff_limit_per_index' => 'int',
        'completion_mode' => 'string',
        'completions' => 'int',
        'managed_by' => 'string',
        'manual_selector' => 'bool',
        'max_failed_indexes' => 'int',
        'parallelism' => 'int',
        'pod_failure_policy' => '\Kubernetes\Client\Model\V1PodFailurePolicy',
        'pod_replacement_policy' => 'string',
        'scheduling' => '\Kubernetes\Client\Model\V1JobSchedulingConfiguration',
        'selector' => '\Kubernetes\Client\Model\V1LabelSelector',
        'success_policy' => '\Kubernetes\Client\Model\V1SuccessPolicy',
        'suspend' => 'bool',
        'template' => '\Kubernetes\Client\Model\V1PodTemplateSpec',
        'ttl_seconds_after_finished' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'active_deadline_seconds' => 'int64',
        'backoff_limit' => 'int32',
        'backoff_limit_per_index' => 'int32',
        'completion_mode' => null,
        'completions' => 'int32',
        'managed_by' => null,
        'manual_selector' => null,
        'max_failed_indexes' => 'int32',
        'parallelism' => 'int32',
        'pod_failure_policy' => null,
        'pod_replacement_policy' => null,
        'scheduling' => null,
        'selector' => null,
        'success_policy' => null,
        'suspend' => null,
        'template' => null,
        'ttl_seconds_after_finished' => 'int32'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'active_deadline_seconds' => false,
        'backoff_limit' => false,
        'backoff_limit_per_index' => false,
        'completion_mode' => false,
        'completions' => false,
        'managed_by' => false,
        'manual_selector' => false,
        'max_failed_indexes' => false,
        'parallelism' => false,
        'pod_failure_policy' => false,
        'pod_replacement_policy' => false,
        'scheduling' => false,
        'selector' => false,
        'success_policy' => false,
        'suspend' => false,
        'template' => false,
        'ttl_seconds_after_finished' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'active_deadline_seconds' => 'activeDeadlineSeconds',
        'backoff_limit' => 'backoffLimit',
        'backoff_limit_per_index' => 'backoffLimitPerIndex',
        'completion_mode' => 'completionMode',
        'completions' => 'completions',
        'managed_by' => 'managedBy',
        'manual_selector' => 'manualSelector',
        'max_failed_indexes' => 'maxFailedIndexes',
        'parallelism' => 'parallelism',
        'pod_failure_policy' => 'podFailurePolicy',
        'pod_replacement_policy' => 'podReplacementPolicy',
        'scheduling' => 'scheduling',
        'selector' => 'selector',
        'success_policy' => 'successPolicy',
        'suspend' => 'suspend',
        'template' => 'template',
        'ttl_seconds_after_finished' => 'ttlSecondsAfterFinished'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'active_deadline_seconds' => 'setActiveDeadlineSeconds',
        'backoff_limit' => 'setBackoffLimit',
        'backoff_limit_per_index' => 'setBackoffLimitPerIndex',
        'completion_mode' => 'setCompletionMode',
        'completions' => 'setCompletions',
        'managed_by' => 'setManagedBy',
        'manual_selector' => 'setManualSelector',
        'max_failed_indexes' => 'setMaxFailedIndexes',
        'parallelism' => 'setParallelism',
        'pod_failure_policy' => 'setPodFailurePolicy',
        'pod_replacement_policy' => 'setPodReplacementPolicy',
        'scheduling' => 'setScheduling',
        'selector' => 'setSelector',
        'success_policy' => 'setSuccessPolicy',
        'suspend' => 'setSuspend',
        'template' => 'setTemplate',
        'ttl_seconds_after_finished' => 'setTtlSecondsAfterFinished'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'active_deadline_seconds' => 'getActiveDeadlineSeconds',
        'backoff_limit' => 'getBackoffLimit',
        'backoff_limit_per_index' => 'getBackoffLimitPerIndex',
        'completion_mode' => 'getCompletionMode',
        'completions' => 'getCompletions',
        'managed_by' => 'getManagedBy',
        'manual_selector' => 'getManualSelector',
        'max_failed_indexes' => 'getMaxFailedIndexes',
        'parallelism' => 'getParallelism',
        'pod_failure_policy' => 'getPodFailurePolicy',
        'pod_replacement_policy' => 'getPodReplacementPolicy',
        'scheduling' => 'getScheduling',
        'selector' => 'getSelector',
        'success_policy' => 'getSuccessPolicy',
        'suspend' => 'getSuspend',
        'template' => 'getTemplate',
        'ttl_seconds_after_finished' => 'getTtlSecondsAfterFinished'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('active_deadline_seconds', $data ?? [], null);
        $this->setIfExists('backoff_limit', $data ?? [], null);
        $this->setIfExists('backoff_limit_per_index', $data ?? [], null);
        $this->setIfExists('completion_mode', $data ?? [], null);
        $this->setIfExists('completions', $data ?? [], null);
        $this->setIfExists('managed_by', $data ?? [], null);
        $this->setIfExists('manual_selector', $data ?? [], null);
        $this->setIfExists('max_failed_indexes', $data ?? [], null);
        $this->setIfExists('parallelism', $data ?? [], null);
        $this->setIfExists('pod_failure_policy', $data ?? [], null);
        $this->setIfExists('pod_replacement_policy', $data ?? [], null);
        $this->setIfExists('scheduling', $data ?? [], null);
        $this->setIfExists('selector', $data ?? [], null);
        $this->setIfExists('success_policy', $data ?? [], null);
        $this->setIfExists('suspend', $data ?? [], null);
        $this->setIfExists('template', $data ?? [], null);
        $this->setIfExists('ttl_seconds_after_finished', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['template'] === null) {
            $invalidProperties[] = "'template' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active_deadline_seconds
     *
     * @return int|null
     */
    public function getActiveDeadlineSeconds()
    {
        return $this->container['active_deadline_seconds'];
    }

    /**
     * Sets active_deadline_seconds
     *
     * @param int|null $active_deadline_seconds Specifies the duration in seconds relative to the startTime that the job may be continuously active before the system tries to terminate it; value must be positive integer. If a Job is suspended (at creation or through an update), this timer will effectively be stopped and reset when the Job is resumed again.
     *
     * @return self
     */
    public function setActiveDeadlineSeconds($active_deadline_seconds)
    {
        if (is_null($active_deadline_seconds)) {
            throw new \InvalidArgumentException('non-nullable active_deadline_seconds cannot be null');
        }
        $this->container['active_deadline_seconds'] = $active_deadline_seconds;

        return $this;
    }

    /**
     * Gets backoff_limit
     *
     * @return int|null
     */
    public function getBackoffLimit()
    {
        return $this->container['backoff_limit'];
    }

    /**
     * Sets backoff_limit
     *
     * @param int|null $backoff_limit Specifies the number of retries before marking this job failed. Defaults to 6, unless backoffLimitPerIndex (only Indexed Job) is specified. When backoffLimitPerIndex is specified, backoffLimit defaults to 2147483647.
     *
     * @return self
     */
    public function setBackoffLimit($backoff_limit)
    {
        if (is_null($backoff_limit)) {
            throw new \InvalidArgumentException('non-nullable backoff_limit cannot be null');
        }
        $this->container['backoff_limit'] = $backoff_limit;

        return $this;
    }

    /**
     * Gets backoff_limit_per_index
     *
     * @return int|null
     */
    public function getBackoffLimitPerIndex()
    {
        return $this->container['backoff_limit_per_index'];
    }

    /**
     * Sets backoff_limit_per_index
     *
     * @param int|null $backoff_limit_per_index Specifies the limit for the number of retries within an index before marking this index as failed. When enabled the number of failures per index is kept in the pod's batch.kubernetes.io/job-index-failure-count annotation. It can only be set when Job's completionMode=Indexed, and the Pod's restart policy is Never. The field is immutable.
     *
     * @return self
     */
    public function setBackoffLimitPerIndex($backoff_limit_per_index)
    {
        if (is_null($backoff_limit_per_index)) {
            throw new \InvalidArgumentException('non-nullable backoff_limit_per_index cannot be null');
        }
        $this->container['backoff_limit_per_index'] = $backoff_limit_per_index;

        return $this;
    }

    /**
     * Gets completion_mode
     *
     * @return string|null
     */
    public function getCompletionMode()
    {
        return $this->container['completion_mode'];
    }

    /**
     * Sets completion_mode
     *
     * @param string|null $completion_mode completionMode specifies how Pod completions are tracked. It can be `NonIndexed` (default) or `Indexed`.  `NonIndexed` means that the Job is considered complete when there have been .spec.completions successfully completed Pods. Each Pod completion is homologous to each other.  `Indexed` means that the Pods of a Job get an associated completion index from 0 to (.spec.completions - 1), available in the annotation batch.kubernetes.io/job-completion-index. The Job is considered complete when there is one successfully completed Pod for each index. When value is `Indexed`, .spec.completions must be specified and `.spec.parallelism` must be less than or equal to 10^5. In addition, The Pod name takes the form `$(job-name)-$(index)-$(random-string)`, the Pod hostname takes the form `$(job-name)-$(index)`.  More completion modes can be added in the future. If the Job controller observes a mode that it doesn't recognize, which is possible during upgrades due to version skew, the controller skips updates for the Job.
     *
     * @return self
     */
    public function setCompletionMode($completion_mode)
    {
        if (is_null($completion_mode)) {
            throw new \InvalidArgumentException('non-nullable completion_mode cannot be null');
        }
        $this->container['completion_mode'] = $completion_mode;

        return $this;
    }

    /**
     * Gets completions
     *
     * @return int|null
     */
    public function getCompletions()
    {
        return $this->container['completions'];
    }

    /**
     * Sets completions
     *
     * @param int|null $completions Specifies the desired number of successfully finished pods the job should be run with.  Setting to null means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
     *
     * @return self
     */
    public function setCompletions($completions)
    {
        if (is_null($completions)) {
            throw new \InvalidArgumentException('non-nullable completions cannot be null');
        }
        $this->container['completions'] = $completions;

        return $this;
    }

    /**
     * Gets managed_by
     *
     * @return string|null
     */
    public function getManagedBy()
    {
        return $this->container['managed_by'];
    }

    /**
     * Sets managed_by
     *
     * @param string|null $managed_by ManagedBy field indicates the controller that manages a Job. The k8s Job controller reconciles jobs which don't have this field at all or the field value is the reserved string `kubernetes.io/job-controller`, but skips reconciling Jobs with a custom value for this field. The value must be a valid domain-prefixed path (e.g. acme.io/foo) - all characters before the first \"/\" must be a valid subdomain as defined by RFC 1123. All characters trailing the first \"/\" must be valid HTTP Path characters as defined by RFC 3986. The value cannot exceed 63 characters. This field is immutable.
     *
     * @return self
     */
    public function setManagedBy($managed_by)
    {
        if (is_null($managed_by)) {
            throw new \InvalidArgumentException('non-nullable managed_by cannot be null');
        }
        $this->container['managed_by'] = $managed_by;

        return $this;
    }

    /**
     * Gets manual_selector
     *
     * @return bool|null
     */
    public function getManualSelector()
    {
        return $this->container['manual_selector'];
    }

    /**
     * Sets manual_selector
     *
     * @param bool|null $manual_selector manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector
     *
     * @return self
     */
    public function setManualSelector($manual_selector)
    {
        if (is_null($manual_selector)) {
            throw new \InvalidArgumentException('non-nullable manual_selector cannot be null');
        }
        $this->container['manual_selector'] = $manual_selector;

        return $this;
    }

    /**
     * Gets max_failed_indexes
     *
     * @return int|null
     */
    public function getMaxFailedIndexes()
    {
        return $this->container['max_failed_indexes'];
    }

    /**
     * Sets max_failed_indexes
     *
     * @param int|null $max_failed_indexes Specifies the maximal number of failed indexes before marking the Job as failed, when backoffLimitPerIndex is set. Once the number of failed indexes exceeds this number the entire Job is marked as Failed and its execution is terminated. When left as null the job continues execution of all of its indexes and is marked with the `Complete` Job condition. It can only be specified when backoffLimitPerIndex is set. It can be null or up to completions. It is required and must be less than or equal to 10^4 when is completions greater than 10^5.
     *
     * @return self
     */
    public function setMaxFailedIndexes($max_failed_indexes)
    {
        if (is_null($max_failed_indexes)) {
            throw new \InvalidArgumentException('non-nullable max_failed_indexes cannot be null');
        }
        $this->container['max_failed_indexes'] = $max_failed_indexes;

        return $this;
    }

    /**
     * Gets parallelism
     *
     * @return int|null
     */
    public function getParallelism()
    {
        return $this->container['parallelism'];
    }

    /**
     * Sets parallelism
     *
     * @param int|null $parallelism Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
     *
     * @return self
     */
    public function setParallelism($parallelism)
    {
        if (is_null($parallelism)) {
            throw new \InvalidArgumentException('non-nullable parallelism cannot be null');
        }
        $this->container['parallelism'] = $parallelism;

        return $this;
    }

    /**
     * Gets pod_failure_policy
     *
     * @return \Kubernetes\Client\Model\V1PodFailurePolicy|null
     */
    public function getPodFailurePolicy()
    {
        return $this->container['pod_failure_policy'];
    }

    /**
     * Sets pod_failure_policy
     *
     * @param \Kubernetes\Client\Model\V1PodFailurePolicy|null $pod_failure_policy pod_failure_policy
     *
     * @return self
     */
    public function setPodFailurePolicy($pod_failure_policy)
    {
        if (is_null($pod_failure_policy)) {
            throw new \InvalidArgumentException('non-nullable pod_failure_policy cannot be null');
        }
        $this->container['pod_failure_policy'] = $pod_failure_policy;

        return $this;
    }

    /**
     * Gets pod_replacement_policy
     *
     * @return string|null
     */
    public function getPodReplacementPolicy()
    {
        return $this->container['pod_replacement_policy'];
    }

    /**
     * Sets pod_replacement_policy
     *
     * @param string|null $pod_replacement_policy podReplacementPolicy specifies when to create replacement Pods. Possible values are: - TerminatingOrFailed means that we recreate pods   when they are terminating (has a metadata.deletionTimestamp) or failed. - Failed means to wait until a previously created Pod is fully terminated (has phase   Failed or Succeeded) before creating a replacement Pod.  When using podFailurePolicy, Failed is the the only allowed value. TerminatingOrFailed and Failed are allowed values when podFailurePolicy is not in use.
     *
     * @return self
     */
    public function setPodReplacementPolicy($pod_replacement_policy)
    {
        if (is_null($pod_replacement_policy)) {
            throw new \InvalidArgumentException('non-nullable pod_replacement_policy cannot be null');
        }
        $this->container['pod_replacement_policy'] = $pod_replacement_policy;

        return $this;
    }

    /**
     * Gets scheduling
     *
     * @return \Kubernetes\Client\Model\V1JobSchedulingConfiguration|null
     */
    public function getScheduling()
    {
        return $this->container['scheduling'];
    }

    /**
     * Sets scheduling
     *
     * @param \Kubernetes\Client\Model\V1JobSchedulingConfiguration|null $scheduling scheduling
     *
     * @return self
     */
    public function setScheduling($scheduling)
    {
        if (is_null($scheduling)) {
            throw new \InvalidArgumentException('non-nullable scheduling cannot be null');
        }
        $this->container['scheduling'] = $scheduling;

        return $this;
    }

    /**
     * Gets selector
     *
     * @return \Kubernetes\Client\Model\V1LabelSelector|null
     */
    public function getSelector()
    {
        return $this->container['selector'];
    }

    /**
     * Sets selector
     *
     * @param \Kubernetes\Client\Model\V1LabelSelector|null $selector selector
     *
     * @return self
     */
    public function setSelector($selector)
    {
        if (is_null($selector)) {
            throw new \InvalidArgumentException('non-nullable selector cannot be null');
        }
        $this->container['selector'] = $selector;

        return $this;
    }

    /**
     * Gets success_policy
     *
     * @return \Kubernetes\Client\Model\V1SuccessPolicy|null
     */
    public function getSuccessPolicy()
    {
        return $this->container['success_policy'];
    }

    /**
     * Sets success_policy
     *
     * @param \Kubernetes\Client\Model\V1SuccessPolicy|null $success_policy success_policy
     *
     * @return self
     */
    public function setSuccessPolicy($success_policy)
    {
        if (is_null($success_policy)) {
            throw new \InvalidArgumentException('non-nullable success_policy cannot be null');
        }
        $this->container['success_policy'] = $success_policy;

        return $this;
    }

    /**
     * Gets suspend
     *
     * @return bool|null
     */
    public function getSuspend()
    {
        return $this->container['suspend'];
    }

    /**
     * Sets suspend
     *
     * @param bool|null $suspend suspend specifies whether the Job controller should create Pods or not. If a Job is created with suspend set to true, no Pods are created by the Job controller. If a Job is suspended after creation (i.e. the flag goes from false to true), the Job controller will delete all active Pods associated with this Job. Users must design their workload to gracefully handle this. Suspending a Job will reset the StartTime field of the Job, effectively resetting the ActiveDeadlineSeconds timer too. Defaults to false.
     *
     * @return self
     */
    public function setSuspend($suspend)
    {
        if (is_null($suspend)) {
            throw new \InvalidArgumentException('non-nullable suspend cannot be null');
        }
        $this->container['suspend'] = $suspend;

        return $this;
    }

    /**
     * Gets template
     *
     * @return \Kubernetes\Client\Model\V1PodTemplateSpec
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param \Kubernetes\Client\Model\V1PodTemplateSpec $template template
     *
     * @return self
     */
    public function setTemplate($template)
    {
        if (is_null($template)) {
            throw new \InvalidArgumentException('non-nullable template cannot be null');
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets ttl_seconds_after_finished
     *
     * @return int|null
     */
    public function getTtlSecondsAfterFinished()
    {
        return $this->container['ttl_seconds_after_finished'];
    }

    /**
     * Sets ttl_seconds_after_finished
     *
     * @param int|null $ttl_seconds_after_finished ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes.
     *
     * @return self
     */
    public function setTtlSecondsAfterFinished($ttl_seconds_after_finished)
    {
        if (is_null($ttl_seconds_after_finished)) {
            throw new \InvalidArgumentException('non-nullable ttl_seconds_after_finished cannot be null');
        }
        $this->container['ttl_seconds_after_finished'] = $ttl_seconds_after_finished;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


