<?php
/**
 * V1PodCertificateProjection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1PodCertificateProjection Class Doc Comment
 *
 * @category Class
 * @description PodCertificateProjection provides a private key and X.509 certificate in the pod filesystem.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1PodCertificateProjection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.PodCertificateProjection';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'certificate_chain_path' => 'string',
        'credential_bundle_path' => 'string',
        'key_path' => 'string',
        'key_type' => 'string',
        'max_expiration_seconds' => 'int',
        'signer_name' => 'string',
        'user' => 'int',
        'user_annotations' => 'array<string,string>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'certificate_chain_path' => null,
        'credential_bundle_path' => null,
        'key_path' => null,
        'key_type' => null,
        'max_expiration_seconds' => 'int32',
        'signer_name' => null,
        'user' => 'int64',
        'user_annotations' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'certificate_chain_path' => false,
        'credential_bundle_path' => false,
        'key_path' => false,
        'key_type' => false,
        'max_expiration_seconds' => false,
        'signer_name' => false,
        'user' => false,
        'user_annotations' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'certificate_chain_path' => 'certificateChainPath',
        'credential_bundle_path' => 'credentialBundlePath',
        'key_path' => 'keyPath',
        'key_type' => 'keyType',
        'max_expiration_seconds' => 'maxExpirationSeconds',
        'signer_name' => 'signerName',
        'user' => 'user',
        'user_annotations' => 'userAnnotations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'certificate_chain_path' => 'setCertificateChainPath',
        'credential_bundle_path' => 'setCredentialBundlePath',
        'key_path' => 'setKeyPath',
        'key_type' => 'setKeyType',
        'max_expiration_seconds' => 'setMaxExpirationSeconds',
        'signer_name' => 'setSignerName',
        'user' => 'setUser',
        'user_annotations' => 'setUserAnnotations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'certificate_chain_path' => 'getCertificateChainPath',
        'credential_bundle_path' => 'getCredentialBundlePath',
        'key_path' => 'getKeyPath',
        'key_type' => 'getKeyType',
        'max_expiration_seconds' => 'getMaxExpirationSeconds',
        'signer_name' => 'getSignerName',
        'user' => 'getUser',
        'user_annotations' => 'getUserAnnotations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('certificate_chain_path', $data ?? [], null);
        $this->setIfExists('credential_bundle_path', $data ?? [], null);
        $this->setIfExists('key_path', $data ?? [], null);
        $this->setIfExists('key_type', $data ?? [], null);
        $this->setIfExists('max_expiration_seconds', $data ?? [], null);
        $this->setIfExists('signer_name', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('user_annotations', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['key_type'] === null) {
            $invalidProperties[] = "'key_type' can't be null";
        }
        if ($this->container['signer_name'] === null) {
            $invalidProperties[] = "'signer_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets certificate_chain_path
     *
     * @return string|null
     */
    public function getCertificateChainPath()
    {
        return $this->container['certificate_chain_path'];
    }

    /**
     * Sets certificate_chain_path
     *
     * @param string|null $certificate_chain_path Write the certificate chain at this path in the projected volume.  Most applications should use credentialBundlePath.  When using keyPath and certificateChainPath, your application needs to check that the key and leaf certificate are consistent, because it is possible to read the files mid-rotation.
     *
     * @return self
     */
    public function setCertificateChainPath($certificate_chain_path)
    {
        if (is_null($certificate_chain_path)) {
            throw new \InvalidArgumentException('non-nullable certificate_chain_path cannot be null');
        }
        $this->container['certificate_chain_path'] = $certificate_chain_path;

        return $this;
    }

    /**
     * Gets credential_bundle_path
     *
     * @return string|null
     */
    public function getCredentialBundlePath()
    {
        return $this->container['credential_bundle_path'];
    }

    /**
     * Sets credential_bundle_path
     *
     * @param string|null $credential_bundle_path Write the credential bundle at this path in the projected volume.  The credential bundle is a single file that contains multiple PEM blocks. The first PEM block is a PRIVATE KEY block, containing a PKCS#8 private key.  The remaining blocks are CERTIFICATE blocks, containing the issued certificate chain from the signer (leaf and any intermediates).  Using credentialBundlePath lets your Pod's application code make a single atomic read that retrieves a consistent key and certificate chain.  If you project them to separate files, your application code will need to additionally check that the leaf certificate was issued to the key.
     *
     * @return self
     */
    public function setCredentialBundlePath($credential_bundle_path)
    {
        if (is_null($credential_bundle_path)) {
            throw new \InvalidArgumentException('non-nullable credential_bundle_path cannot be null');
        }
        $this->container['credential_bundle_path'] = $credential_bundle_path;

        return $this;
    }

    /**
     * Gets key_path
     *
     * @return string|null
     */
    public function getKeyPath()
    {
        return $this->container['key_path'];
    }

    /**
     * Sets key_path
     *
     * @param string|null $key_path Write the key at this path in the projected volume.  Most applications should use credentialBundlePath.  When using keyPath and certificateChainPath, your application needs to check that the key and leaf certificate are consistent, because it is possible to read the files mid-rotation.
     *
     * @return self
     */
    public function setKeyPath($key_path)
    {
        if (is_null($key_path)) {
            throw new \InvalidArgumentException('non-nullable key_path cannot be null');
        }
        $this->container['key_path'] = $key_path;

        return $this;
    }

    /**
     * Gets key_type
     *
     * @return string
     */
    public function getKeyType()
    {
        return $this->container['key_type'];
    }

    /**
     * Sets key_type
     *
     * @param string $key_type The type of keypair Kubelet will generate for the pod.  Valid values are \"RSA3072\", \"RSA4096\", \"ECDSAP256\", \"ECDSAP384\", \"ECDSAP521\", and \"ED25519\".
     *
     * @return self
     */
    public function setKeyType($key_type)
    {
        if (is_null($key_type)) {
            throw new \InvalidArgumentException('non-nullable key_type cannot be null');
        }
        $this->container['key_type'] = $key_type;

        return $this;
    }

    /**
     * Gets max_expiration_seconds
     *
     * @return int|null
     */
    public function getMaxExpirationSeconds()
    {
        return $this->container['max_expiration_seconds'];
    }

    /**
     * Sets max_expiration_seconds
     *
     * @param int|null $max_expiration_seconds maxExpirationSeconds is the maximum lifetime permitted for the certificate.  Kubelet copies this value verbatim into the PodCertificateRequests it generates for this projection.  If omitted, kube-apiserver will set it to 86400(24 hours). kube-apiserver will reject values shorter than 3600 (1 hour).  The maximum allowable value is 7862400 (91 days).  The signer implementation is then free to issue a certificate with any lifetime *shorter* than MaxExpirationSeconds, but no shorter than 3600 seconds (1 hour).  This constraint is enforced by kube-apiserver. `kubernetes.io` signers will never issue certificates with a lifetime longer than 24 hours.
     *
     * @return self
     */
    public function setMaxExpirationSeconds($max_expiration_seconds)
    {
        if (is_null($max_expiration_seconds)) {
            throw new \InvalidArgumentException('non-nullable max_expiration_seconds cannot be null');
        }
        $this->container['max_expiration_seconds'] = $max_expiration_seconds;

        return $this;
    }

    /**
     * Gets signer_name
     *
     * @return string
     */
    public function getSignerName()
    {
        return $this->container['signer_name'];
    }

    /**
     * Sets signer_name
     *
     * @param string $signer_name Kubelet's generated CSRs will be addressed to this signer.
     *
     * @return self
     */
    public function setSignerName($signer_name)
    {
        if (is_null($signer_name)) {
            throw new \InvalidArgumentException('non-nullable signer_name cannot be null');
        }
        $this->container['signer_name'] = $signer_name;

        return $this;
    }

    /**
     * Gets user
     *
     * @return int|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param int|null $user user is Optional: The owner UID of the created file. If specified, the item-level user field takes precedence over defaultUser. (Alpha) This field requires the AtomicWriteVolumeUserFields feature gate to be enabled.
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets user_annotations
     *
     * @return array<string,string>|null
     */
    public function getUserAnnotations()
    {
        return $this->container['user_annotations'];
    }

    /**
     * Sets user_annotations
     *
     * @param array<string,string>|null $user_annotations userAnnotations allow pod authors to pass additional information to the signer implementation.  Kubernetes does not restrict or validate this metadata in any way.  These values are copied verbatim into the `spec.unverifiedUserAnnotations` field of the PodCertificateRequest objects that Kubelet creates.  Entries are subject to the same validation as object metadata annotations, with the addition that all keys must be domain-prefixed. No restrictions are placed on values, except an overall size limitation on the entire field.  Signers should document the keys and values they support. Signers should deny requests that contain keys they do not recognize.
     *
     * @return self
     */
    public function setUserAnnotations($user_annotations)
    {
        if (is_null($user_annotations)) {
            throw new \InvalidArgumentException('non-nullable user_annotations cannot be null');
        }
        $this->container['user_annotations'] = $user_annotations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


