<?php
/**
 * V1PodDisruptionBudgetStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1PodDisruptionBudgetStatus Class Doc Comment
 *
 * @category Class
 * @description PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1PodDisruptionBudgetStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.PodDisruptionBudgetStatus';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'conditions' => '\Kubernetes\Client\Model\V1Condition[]',
        'current_healthy' => 'int',
        'desired_healthy' => 'int',
        'disrupted_pods' => 'array<string,\DateTime>',
        'disruptions_allowed' => 'int',
        'expected_pods' => 'int',
        'observed_generation' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'conditions' => null,
        'current_healthy' => 'int32',
        'desired_healthy' => 'int32',
        'disrupted_pods' => 'date-time',
        'disruptions_allowed' => 'int32',
        'expected_pods' => 'int32',
        'observed_generation' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'conditions' => false,
        'current_healthy' => false,
        'desired_healthy' => false,
        'disrupted_pods' => false,
        'disruptions_allowed' => false,
        'expected_pods' => false,
        'observed_generation' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'conditions' => 'conditions',
        'current_healthy' => 'currentHealthy',
        'desired_healthy' => 'desiredHealthy',
        'disrupted_pods' => 'disruptedPods',
        'disruptions_allowed' => 'disruptionsAllowed',
        'expected_pods' => 'expectedPods',
        'observed_generation' => 'observedGeneration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'conditions' => 'setConditions',
        'current_healthy' => 'setCurrentHealthy',
        'desired_healthy' => 'setDesiredHealthy',
        'disrupted_pods' => 'setDisruptedPods',
        'disruptions_allowed' => 'setDisruptionsAllowed',
        'expected_pods' => 'setExpectedPods',
        'observed_generation' => 'setObservedGeneration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'conditions' => 'getConditions',
        'current_healthy' => 'getCurrentHealthy',
        'desired_healthy' => 'getDesiredHealthy',
        'disrupted_pods' => 'getDisruptedPods',
        'disruptions_allowed' => 'getDisruptionsAllowed',
        'expected_pods' => 'getExpectedPods',
        'observed_generation' => 'getObservedGeneration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('conditions', $data ?? [], null);
        $this->setIfExists('current_healthy', $data ?? [], null);
        $this->setIfExists('desired_healthy', $data ?? [], null);
        $this->setIfExists('disrupted_pods', $data ?? [], null);
        $this->setIfExists('disruptions_allowed', $data ?? [], null);
        $this->setIfExists('expected_pods', $data ?? [], null);
        $this->setIfExists('observed_generation', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets conditions
     *
     * @return \Kubernetes\Client\Model\V1Condition[]|null
     */
    public function getConditions()
    {
        return $this->container['conditions'];
    }

    /**
     * Sets conditions
     *
     * @param \Kubernetes\Client\Model\V1Condition[]|null $conditions Conditions contain conditions for PDB. The disruption controller sets the DisruptionAllowed condition. The following are known values for the reason field (additional reasons could be added in the future): - SyncFailed: The controller encountered an error and wasn't able to compute               the number of allowed disruptions. Therefore no disruptions are               allowed and the status of the condition will be False. - InsufficientPods: The number of pods are either at or below the number                     required by the PodDisruptionBudget. No disruptions are                     allowed and the status of the condition will be False. - SufficientPods: There are more pods than required by the PodDisruptionBudget.                   The condition will be True, and the number of allowed                   disruptions are provided by the disruptionsAllowed property.
     *
     * @return self
     */
    public function setConditions($conditions)
    {
        if (is_null($conditions)) {
            throw new \InvalidArgumentException('non-nullable conditions cannot be null');
        }
        $this->container['conditions'] = $conditions;

        return $this;
    }

    /**
     * Gets current_healthy
     *
     * @return int|null
     */
    public function getCurrentHealthy()
    {
        return $this->container['current_healthy'];
    }

    /**
     * Sets current_healthy
     *
     * @param int|null $current_healthy current number of healthy pods
     *
     * @return self
     */
    public function setCurrentHealthy($current_healthy)
    {
        if (is_null($current_healthy)) {
            throw new \InvalidArgumentException('non-nullable current_healthy cannot be null');
        }
        $this->container['current_healthy'] = $current_healthy;

        return $this;
    }

    /**
     * Gets desired_healthy
     *
     * @return int|null
     */
    public function getDesiredHealthy()
    {
        return $this->container['desired_healthy'];
    }

    /**
     * Sets desired_healthy
     *
     * @param int|null $desired_healthy minimum desired number of healthy pods
     *
     * @return self
     */
    public function setDesiredHealthy($desired_healthy)
    {
        if (is_null($desired_healthy)) {
            throw new \InvalidArgumentException('non-nullable desired_healthy cannot be null');
        }
        $this->container['desired_healthy'] = $desired_healthy;

        return $this;
    }

    /**
     * Gets disrupted_pods
     *
     * @return array<string,\DateTime>|null
     */
    public function getDisruptedPods()
    {
        return $this->container['disrupted_pods'];
    }

    /**
     * Sets disrupted_pods
     *
     * @param array<string,\DateTime>|null $disrupted_pods DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn't occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions.
     *
     * @return self
     */
    public function setDisruptedPods($disrupted_pods)
    {
        if (is_null($disrupted_pods)) {
            throw new \InvalidArgumentException('non-nullable disrupted_pods cannot be null');
        }
        $this->container['disrupted_pods'] = $disrupted_pods;

        return $this;
    }

    /**
     * Gets disruptions_allowed
     *
     * @return int|null
     */
    public function getDisruptionsAllowed()
    {
        return $this->container['disruptions_allowed'];
    }

    /**
     * Sets disruptions_allowed
     *
     * @param int|null $disruptions_allowed Number of pod disruptions that are currently allowed.
     *
     * @return self
     */
    public function setDisruptionsAllowed($disruptions_allowed)
    {
        if (is_null($disruptions_allowed)) {
            throw new \InvalidArgumentException('non-nullable disruptions_allowed cannot be null');
        }
        $this->container['disruptions_allowed'] = $disruptions_allowed;

        return $this;
    }

    /**
     * Gets expected_pods
     *
     * @return int|null
     */
    public function getExpectedPods()
    {
        return $this->container['expected_pods'];
    }

    /**
     * Sets expected_pods
     *
     * @param int|null $expected_pods total number of pods counted by this disruption budget
     *
     * @return self
     */
    public function setExpectedPods($expected_pods)
    {
        if (is_null($expected_pods)) {
            throw new \InvalidArgumentException('non-nullable expected_pods cannot be null');
        }
        $this->container['expected_pods'] = $expected_pods;

        return $this;
    }

    /**
     * Gets observed_generation
     *
     * @return int|null
     */
    public function getObservedGeneration()
    {
        return $this->container['observed_generation'];
    }

    /**
     * Sets observed_generation
     *
     * @param int|null $observed_generation Most recent generation observed when updating this PDB status. DisruptionsAllowed and other status information is valid only if observedGeneration equals to PDB's object generation.
     *
     * @return self
     */
    public function setObservedGeneration($observed_generation)
    {
        if (is_null($observed_generation)) {
            throw new \InvalidArgumentException('non-nullable observed_generation cannot be null');
        }
        $this->container['observed_generation'] = $observed_generation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


