<?php
/**
 * V1PodCertificateRequestSpec
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1PodCertificateRequestSpec Class Doc Comment
 *
 * @category Class
 * @description PodCertificateRequestSpec describes the certificate request.  All fields are immutable after creation.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1PodCertificateRequestSpec implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.PodCertificateRequestSpec';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'max_expiration_seconds' => 'int',
        'node_name' => 'string',
        'node_uid' => 'string',
        'pod_name' => 'string',
        'pod_uid' => 'string',
        'service_account_name' => 'string',
        'service_account_uid' => 'string',
        'signer_name' => 'string',
        'stub_pkcs10_request' => 'string',
        'unverified_user_annotations' => 'array<string,string>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'max_expiration_seconds' => 'int32',
        'node_name' => null,
        'node_uid' => null,
        'pod_name' => null,
        'pod_uid' => null,
        'service_account_name' => null,
        'service_account_uid' => null,
        'signer_name' => null,
        'stub_pkcs10_request' => 'byte',
        'unverified_user_annotations' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'max_expiration_seconds' => false,
        'node_name' => false,
        'node_uid' => false,
        'pod_name' => false,
        'pod_uid' => false,
        'service_account_name' => false,
        'service_account_uid' => false,
        'signer_name' => false,
        'stub_pkcs10_request' => false,
        'unverified_user_annotations' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'max_expiration_seconds' => 'maxExpirationSeconds',
        'node_name' => 'nodeName',
        'node_uid' => 'nodeUID',
        'pod_name' => 'podName',
        'pod_uid' => 'podUID',
        'service_account_name' => 'serviceAccountName',
        'service_account_uid' => 'serviceAccountUID',
        'signer_name' => 'signerName',
        'stub_pkcs10_request' => 'stubPKCS10Request',
        'unverified_user_annotations' => 'unverifiedUserAnnotations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'max_expiration_seconds' => 'setMaxExpirationSeconds',
        'node_name' => 'setNodeName',
        'node_uid' => 'setNodeUid',
        'pod_name' => 'setPodName',
        'pod_uid' => 'setPodUid',
        'service_account_name' => 'setServiceAccountName',
        'service_account_uid' => 'setServiceAccountUid',
        'signer_name' => 'setSignerName',
        'stub_pkcs10_request' => 'setStubPkcs10Request',
        'unverified_user_annotations' => 'setUnverifiedUserAnnotations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'max_expiration_seconds' => 'getMaxExpirationSeconds',
        'node_name' => 'getNodeName',
        'node_uid' => 'getNodeUid',
        'pod_name' => 'getPodName',
        'pod_uid' => 'getPodUid',
        'service_account_name' => 'getServiceAccountName',
        'service_account_uid' => 'getServiceAccountUid',
        'signer_name' => 'getSignerName',
        'stub_pkcs10_request' => 'getStubPkcs10Request',
        'unverified_user_annotations' => 'getUnverifiedUserAnnotations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('max_expiration_seconds', $data ?? [], null);
        $this->setIfExists('node_name', $data ?? [], null);
        $this->setIfExists('node_uid', $data ?? [], null);
        $this->setIfExists('pod_name', $data ?? [], null);
        $this->setIfExists('pod_uid', $data ?? [], null);
        $this->setIfExists('service_account_name', $data ?? [], null);
        $this->setIfExists('service_account_uid', $data ?? [], null);
        $this->setIfExists('signer_name', $data ?? [], null);
        $this->setIfExists('stub_pkcs10_request', $data ?? [], null);
        $this->setIfExists('unverified_user_annotations', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['node_name'] === null) {
            $invalidProperties[] = "'node_name' can't be null";
        }
        if ($this->container['node_uid'] === null) {
            $invalidProperties[] = "'node_uid' can't be null";
        }
        if ($this->container['pod_name'] === null) {
            $invalidProperties[] = "'pod_name' can't be null";
        }
        if ($this->container['pod_uid'] === null) {
            $invalidProperties[] = "'pod_uid' can't be null";
        }
        if ($this->container['service_account_name'] === null) {
            $invalidProperties[] = "'service_account_name' can't be null";
        }
        if ($this->container['service_account_uid'] === null) {
            $invalidProperties[] = "'service_account_uid' can't be null";
        }
        if ($this->container['signer_name'] === null) {
            $invalidProperties[] = "'signer_name' can't be null";
        }
        if ($this->container['stub_pkcs10_request'] === null) {
            $invalidProperties[] = "'stub_pkcs10_request' can't be null";
        }
        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['stub_pkcs10_request'])) {
            $invalidProperties[] = "invalid value for 'stub_pkcs10_request', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets max_expiration_seconds
     *
     * @return int|null
     */
    public function getMaxExpirationSeconds()
    {
        return $this->container['max_expiration_seconds'];
    }

    /**
     * Sets max_expiration_seconds
     *
     * @param int|null $max_expiration_seconds maxExpirationSeconds is the maximum lifetime permitted for the certificate.  If omitted, kube-apiserver will set it to 86400(24 hours). kube-apiserver will reject values shorter than 3600 (1 hour).  The maximum allowable value is 7862400 (91 days).  The signer implementation is then free to issue a certificate with any lifetime *shorter* than MaxExpirationSeconds, but no shorter than 3600 seconds (1 hour).  This constraint is enforced by kube-apiserver. `kubernetes.io` signers will never issue certificates with a lifetime longer than 24 hours.
     *
     * @return self
     */
    public function setMaxExpirationSeconds($max_expiration_seconds)
    {
        if (is_null($max_expiration_seconds)) {
            throw new \InvalidArgumentException('non-nullable max_expiration_seconds cannot be null');
        }
        $this->container['max_expiration_seconds'] = $max_expiration_seconds;

        return $this;
    }

    /**
     * Gets node_name
     *
     * @return string
     */
    public function getNodeName()
    {
        return $this->container['node_name'];
    }

    /**
     * Sets node_name
     *
     * @param string $node_name nodeName is the name of the node the pod is assigned to.
     *
     * @return self
     */
    public function setNodeName($node_name)
    {
        if (is_null($node_name)) {
            throw new \InvalidArgumentException('non-nullable node_name cannot be null');
        }
        $this->container['node_name'] = $node_name;

        return $this;
    }

    /**
     * Gets node_uid
     *
     * @return string
     */
    public function getNodeUid()
    {
        return $this->container['node_uid'];
    }

    /**
     * Sets node_uid
     *
     * @param string $node_uid nodeUID is the UID of the node the pod is assigned to.
     *
     * @return self
     */
    public function setNodeUid($node_uid)
    {
        if (is_null($node_uid)) {
            throw new \InvalidArgumentException('non-nullable node_uid cannot be null');
        }
        $this->container['node_uid'] = $node_uid;

        return $this;
    }

    /**
     * Gets pod_name
     *
     * @return string
     */
    public function getPodName()
    {
        return $this->container['pod_name'];
    }

    /**
     * Sets pod_name
     *
     * @param string $pod_name podName is the name of the pod into which the certificate will be mounted.
     *
     * @return self
     */
    public function setPodName($pod_name)
    {
        if (is_null($pod_name)) {
            throw new \InvalidArgumentException('non-nullable pod_name cannot be null');
        }
        $this->container['pod_name'] = $pod_name;

        return $this;
    }

    /**
     * Gets pod_uid
     *
     * @return string
     */
    public function getPodUid()
    {
        return $this->container['pod_uid'];
    }

    /**
     * Sets pod_uid
     *
     * @param string $pod_uid podUID is the UID of the pod into which the certificate will be mounted.
     *
     * @return self
     */
    public function setPodUid($pod_uid)
    {
        if (is_null($pod_uid)) {
            throw new \InvalidArgumentException('non-nullable pod_uid cannot be null');
        }
        $this->container['pod_uid'] = $pod_uid;

        return $this;
    }

    /**
     * Gets service_account_name
     *
     * @return string
     */
    public function getServiceAccountName()
    {
        return $this->container['service_account_name'];
    }

    /**
     * Sets service_account_name
     *
     * @param string $service_account_name serviceAccountName is the name of the service account the pod is running as.
     *
     * @return self
     */
    public function setServiceAccountName($service_account_name)
    {
        if (is_null($service_account_name)) {
            throw new \InvalidArgumentException('non-nullable service_account_name cannot be null');
        }
        $this->container['service_account_name'] = $service_account_name;

        return $this;
    }

    /**
     * Gets service_account_uid
     *
     * @return string
     */
    public function getServiceAccountUid()
    {
        return $this->container['service_account_uid'];
    }

    /**
     * Sets service_account_uid
     *
     * @param string $service_account_uid serviceAccountUID is the UID of the service account the pod is running as.
     *
     * @return self
     */
    public function setServiceAccountUid($service_account_uid)
    {
        if (is_null($service_account_uid)) {
            throw new \InvalidArgumentException('non-nullable service_account_uid cannot be null');
        }
        $this->container['service_account_uid'] = $service_account_uid;

        return $this;
    }

    /**
     * Gets signer_name
     *
     * @return string
     */
    public function getSignerName()
    {
        return $this->container['signer_name'];
    }

    /**
     * Sets signer_name
     *
     * @param string $signer_name signerName indicates the requested signer.  All signer names beginning with `kubernetes.io` are reserved for use by the Kubernetes project.  There is currently one well-known signer documented by the Kubernetes project, `kubernetes.io/kube-apiserver-client-pod`, which will issue client certificates understood by kube-apiserver.  It is currently unimplemented.
     *
     * @return self
     */
    public function setSignerName($signer_name)
    {
        if (is_null($signer_name)) {
            throw new \InvalidArgumentException('non-nullable signer_name cannot be null');
        }
        $this->container['signer_name'] = $signer_name;

        return $this;
    }

    /**
     * Gets stub_pkcs10_request
     *
     * @return string
     */
    public function getStubPkcs10Request()
    {
        return $this->container['stub_pkcs10_request'];
    }

    /**
     * Sets stub_pkcs10_request
     *
     * @param string $stub_pkcs10_request A PKCS#10 certificate signing request (DER-serialized) generated by Kubelet using the subject private key.  Most signer implementations will ignore the contents of the CSR except to extract the subject public key. The API server automatically verifies the CSR signature during admission, so the signer does not need to repeat the verification.  CSRs generated by kubelet are completely empty.  The subject public key must be one of RSA3072, RSA4096, ECDSAP256, ECDSAP384, ECDSAP521, or ED25519. Note that this list may be expanded in the future.  Signer implementations do not need to support all key types supported by kube-apiserver and kubelet.  If a signer does not support the key type used for a given PodCertificateRequest, it must deny the request by setting a status.conditions entry with a type of \"Denied\" and a reason of \"UnsupportedKeyType\". It may also suggest a key type that it does support in the message field.
     *
     * @return self
     */
    public function setStubPkcs10Request($stub_pkcs10_request)
    {
        if (is_null($stub_pkcs10_request)) {
            throw new \InvalidArgumentException('non-nullable stub_pkcs10_request cannot be null');
        }
        if ((!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", ObjectSerializer::toString($stub_pkcs10_request)))) {
            throw new \InvalidArgumentException("invalid value for \$stub_pkcs10_request when calling V1PodCertificateRequestSpec., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['stub_pkcs10_request'] = $stub_pkcs10_request;

        return $this;
    }

    /**
     * Gets unverified_user_annotations
     *
     * @return array<string,string>|null
     */
    public function getUnverifiedUserAnnotations()
    {
        return $this->container['unverified_user_annotations'];
    }

    /**
     * Sets unverified_user_annotations
     *
     * @param array<string,string>|null $unverified_user_annotations unverifiedUserAnnotations allow pod authors to pass additional information to the signer implementation.  Kubernetes does not restrict or validate this metadata in any way.  Entries are subject to the same validation as object metadata annotations, with the addition that all keys must be domain-prefixed. No restrictions are placed on values, except an overall size limitation on the entire field.  Signers should document the keys and values they support.  Signers should deny requests that contain keys they do not recognize.
     *
     * @return self
     */
    public function setUnverifiedUserAnnotations($unverified_user_annotations)
    {
        if (is_null($unverified_user_annotations)) {
            throw new \InvalidArgumentException('non-nullable unverified_user_annotations cannot be null');
        }
        $this->container['unverified_user_annotations'] = $unverified_user_annotations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


