<?php
/**
 * V1ScaleIOVolumeSource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1ScaleIOVolumeSource Class Doc Comment
 *
 * @category Class
 * @description ScaleIOVolumeSource represents a persistent ScaleIO volume
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1ScaleIOVolumeSource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.ScaleIOVolumeSource';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'fs_type' => 'string',
        'gateway' => 'string',
        'protection_domain' => 'string',
        'read_only' => 'bool',
        'secret_ref' => '\Kubernetes\Client\Model\V1LocalObjectReference',
        'ssl_enabled' => 'bool',
        'storage_mode' => 'string',
        'storage_pool' => 'string',
        'system' => 'string',
        'volume_name' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'fs_type' => null,
        'gateway' => null,
        'protection_domain' => null,
        'read_only' => null,
        'secret_ref' => null,
        'ssl_enabled' => null,
        'storage_mode' => null,
        'storage_pool' => null,
        'system' => null,
        'volume_name' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'fs_type' => false,
        'gateway' => false,
        'protection_domain' => false,
        'read_only' => false,
        'secret_ref' => false,
        'ssl_enabled' => false,
        'storage_mode' => false,
        'storage_pool' => false,
        'system' => false,
        'volume_name' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fs_type' => 'fsType',
        'gateway' => 'gateway',
        'protection_domain' => 'protectionDomain',
        'read_only' => 'readOnly',
        'secret_ref' => 'secretRef',
        'ssl_enabled' => 'sslEnabled',
        'storage_mode' => 'storageMode',
        'storage_pool' => 'storagePool',
        'system' => 'system',
        'volume_name' => 'volumeName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fs_type' => 'setFsType',
        'gateway' => 'setGateway',
        'protection_domain' => 'setProtectionDomain',
        'read_only' => 'setReadOnly',
        'secret_ref' => 'setSecretRef',
        'ssl_enabled' => 'setSslEnabled',
        'storage_mode' => 'setStorageMode',
        'storage_pool' => 'setStoragePool',
        'system' => 'setSystem',
        'volume_name' => 'setVolumeName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fs_type' => 'getFsType',
        'gateway' => 'getGateway',
        'protection_domain' => 'getProtectionDomain',
        'read_only' => 'getReadOnly',
        'secret_ref' => 'getSecretRef',
        'ssl_enabled' => 'getSslEnabled',
        'storage_mode' => 'getStorageMode',
        'storage_pool' => 'getStoragePool',
        'system' => 'getSystem',
        'volume_name' => 'getVolumeName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fs_type', $data ?? [], null);
        $this->setIfExists('gateway', $data ?? [], null);
        $this->setIfExists('protection_domain', $data ?? [], null);
        $this->setIfExists('read_only', $data ?? [], null);
        $this->setIfExists('secret_ref', $data ?? [], null);
        $this->setIfExists('ssl_enabled', $data ?? [], null);
        $this->setIfExists('storage_mode', $data ?? [], null);
        $this->setIfExists('storage_pool', $data ?? [], null);
        $this->setIfExists('system', $data ?? [], null);
        $this->setIfExists('volume_name', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['gateway'] === null) {
            $invalidProperties[] = "'gateway' can't be null";
        }
        if ($this->container['secret_ref'] === null) {
            $invalidProperties[] = "'secret_ref' can't be null";
        }
        if ($this->container['system'] === null) {
            $invalidProperties[] = "'system' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fs_type
     *
     * @return string|null
     */
    public function getFsType()
    {
        return $this->container['fs_type'];
    }

    /**
     * Sets fs_type
     *
     * @param string|null $fs_type fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\".
     *
     * @return self
     */
    public function setFsType($fs_type)
    {
        if (is_null($fs_type)) {
            throw new \InvalidArgumentException('non-nullable fs_type cannot be null');
        }
        $this->container['fs_type'] = $fs_type;

        return $this;
    }

    /**
     * Gets gateway
     *
     * @return string
     */
    public function getGateway()
    {
        return $this->container['gateway'];
    }

    /**
     * Sets gateway
     *
     * @param string $gateway gateway is the host address of the ScaleIO API Gateway.
     *
     * @return self
     */
    public function setGateway($gateway)
    {
        if (is_null($gateway)) {
            throw new \InvalidArgumentException('non-nullable gateway cannot be null');
        }
        $this->container['gateway'] = $gateway;

        return $this;
    }

    /**
     * Gets protection_domain
     *
     * @return string|null
     */
    public function getProtectionDomain()
    {
        return $this->container['protection_domain'];
    }

    /**
     * Sets protection_domain
     *
     * @param string|null $protection_domain protectionDomain is the name of the ScaleIO Protection Domain for the configured storage.
     *
     * @return self
     */
    public function setProtectionDomain($protection_domain)
    {
        if (is_null($protection_domain)) {
            throw new \InvalidArgumentException('non-nullable protection_domain cannot be null');
        }
        $this->container['protection_domain'] = $protection_domain;

        return $this;
    }

    /**
     * Gets read_only
     *
     * @return bool|null
     */
    public function getReadOnly()
    {
        return $this->container['read_only'];
    }

    /**
     * Sets read_only
     *
     * @param bool|null $read_only readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
     *
     * @return self
     */
    public function setReadOnly($read_only)
    {
        if (is_null($read_only)) {
            throw new \InvalidArgumentException('non-nullable read_only cannot be null');
        }
        $this->container['read_only'] = $read_only;

        return $this;
    }

    /**
     * Gets secret_ref
     *
     * @return \Kubernetes\Client\Model\V1LocalObjectReference
     */
    public function getSecretRef()
    {
        return $this->container['secret_ref'];
    }

    /**
     * Sets secret_ref
     *
     * @param \Kubernetes\Client\Model\V1LocalObjectReference $secret_ref secret_ref
     *
     * @return self
     */
    public function setSecretRef($secret_ref)
    {
        if (is_null($secret_ref)) {
            throw new \InvalidArgumentException('non-nullable secret_ref cannot be null');
        }
        $this->container['secret_ref'] = $secret_ref;

        return $this;
    }

    /**
     * Gets ssl_enabled
     *
     * @return bool|null
     */
    public function getSslEnabled()
    {
        return $this->container['ssl_enabled'];
    }

    /**
     * Sets ssl_enabled
     *
     * @param bool|null $ssl_enabled sslEnabled Flag enable/disable SSL communication with Gateway, default false
     *
     * @return self
     */
    public function setSslEnabled($ssl_enabled)
    {
        if (is_null($ssl_enabled)) {
            throw new \InvalidArgumentException('non-nullable ssl_enabled cannot be null');
        }
        $this->container['ssl_enabled'] = $ssl_enabled;

        return $this;
    }

    /**
     * Gets storage_mode
     *
     * @return string|null
     */
    public function getStorageMode()
    {
        return $this->container['storage_mode'];
    }

    /**
     * Sets storage_mode
     *
     * @param string|null $storage_mode storageMode indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned.
     *
     * @return self
     */
    public function setStorageMode($storage_mode)
    {
        if (is_null($storage_mode)) {
            throw new \InvalidArgumentException('non-nullable storage_mode cannot be null');
        }
        $this->container['storage_mode'] = $storage_mode;

        return $this;
    }

    /**
     * Gets storage_pool
     *
     * @return string|null
     */
    public function getStoragePool()
    {
        return $this->container['storage_pool'];
    }

    /**
     * Sets storage_pool
     *
     * @param string|null $storage_pool storagePool is the ScaleIO Storage Pool associated with the protection domain.
     *
     * @return self
     */
    public function setStoragePool($storage_pool)
    {
        if (is_null($storage_pool)) {
            throw new \InvalidArgumentException('non-nullable storage_pool cannot be null');
        }
        $this->container['storage_pool'] = $storage_pool;

        return $this;
    }

    /**
     * Gets system
     *
     * @return string
     */
    public function getSystem()
    {
        return $this->container['system'];
    }

    /**
     * Sets system
     *
     * @param string $system system is the name of the storage system as configured in ScaleIO.
     *
     * @return self
     */
    public function setSystem($system)
    {
        if (is_null($system)) {
            throw new \InvalidArgumentException('non-nullable system cannot be null');
        }
        $this->container['system'] = $system;

        return $this;
    }

    /**
     * Gets volume_name
     *
     * @return string|null
     */
    public function getVolumeName()
    {
        return $this->container['volume_name'];
    }

    /**
     * Sets volume_name
     *
     * @param string|null $volume_name volumeName is the name of a volume already created in the ScaleIO system that is associated with this volume source.
     *
     * @return self
     */
    public function setVolumeName($volume_name)
    {
        if (is_null($volume_name)) {
            throw new \InvalidArgumentException('non-nullable volume_name cannot be null');
        }
        $this->container['volume_name'] = $volume_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


