<?php
/**
 * V1ServiceSpec
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1ServiceSpec Class Doc Comment
 *
 * @category Class
 * @description ServiceSpec describes the attributes that a user creates on a service.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1ServiceSpec implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.ServiceSpec';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'allocate_load_balancer_node_ports' => 'bool',
        'cluster_ip' => 'string',
        'cluster_ips' => 'string[]',
        'external_ips' => 'string[]',
        'external_name' => 'string',
        'external_traffic_policy' => 'string',
        'health_check_node_port' => 'int',
        'internal_traffic_policy' => 'string',
        'ip_families' => 'string[]',
        'ip_family_policy' => 'string',
        'load_balancer_class' => 'string',
        'load_balancer_ip' => 'string',
        'load_balancer_source_ranges' => 'string[]',
        'ports' => '\Kubernetes\Client\Model\V1ServicePort[]',
        'publish_not_ready_addresses' => 'bool',
        'selector' => 'array<string,string>',
        'session_affinity' => 'string',
        'session_affinity_config' => '\Kubernetes\Client\Model\V1SessionAffinityConfig',
        'traffic_distribution' => 'string',
        'type' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'allocate_load_balancer_node_ports' => null,
        'cluster_ip' => null,
        'cluster_ips' => null,
        'external_ips' => null,
        'external_name' => null,
        'external_traffic_policy' => null,
        'health_check_node_port' => 'int32',
        'internal_traffic_policy' => null,
        'ip_families' => null,
        'ip_family_policy' => null,
        'load_balancer_class' => null,
        'load_balancer_ip' => null,
        'load_balancer_source_ranges' => null,
        'ports' => null,
        'publish_not_ready_addresses' => null,
        'selector' => null,
        'session_affinity' => null,
        'session_affinity_config' => null,
        'traffic_distribution' => null,
        'type' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'allocate_load_balancer_node_ports' => false,
        'cluster_ip' => false,
        'cluster_ips' => false,
        'external_ips' => false,
        'external_name' => false,
        'external_traffic_policy' => false,
        'health_check_node_port' => false,
        'internal_traffic_policy' => false,
        'ip_families' => false,
        'ip_family_policy' => false,
        'load_balancer_class' => false,
        'load_balancer_ip' => false,
        'load_balancer_source_ranges' => false,
        'ports' => false,
        'publish_not_ready_addresses' => false,
        'selector' => false,
        'session_affinity' => false,
        'session_affinity_config' => false,
        'traffic_distribution' => false,
        'type' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allocate_load_balancer_node_ports' => 'allocateLoadBalancerNodePorts',
        'cluster_ip' => 'clusterIP',
        'cluster_ips' => 'clusterIPs',
        'external_ips' => 'externalIPs',
        'external_name' => 'externalName',
        'external_traffic_policy' => 'externalTrafficPolicy',
        'health_check_node_port' => 'healthCheckNodePort',
        'internal_traffic_policy' => 'internalTrafficPolicy',
        'ip_families' => 'ipFamilies',
        'ip_family_policy' => 'ipFamilyPolicy',
        'load_balancer_class' => 'loadBalancerClass',
        'load_balancer_ip' => 'loadBalancerIP',
        'load_balancer_source_ranges' => 'loadBalancerSourceRanges',
        'ports' => 'ports',
        'publish_not_ready_addresses' => 'publishNotReadyAddresses',
        'selector' => 'selector',
        'session_affinity' => 'sessionAffinity',
        'session_affinity_config' => 'sessionAffinityConfig',
        'traffic_distribution' => 'trafficDistribution',
        'type' => 'type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allocate_load_balancer_node_ports' => 'setAllocateLoadBalancerNodePorts',
        'cluster_ip' => 'setClusterIp',
        'cluster_ips' => 'setClusterIps',
        'external_ips' => 'setExternalIps',
        'external_name' => 'setExternalName',
        'external_traffic_policy' => 'setExternalTrafficPolicy',
        'health_check_node_port' => 'setHealthCheckNodePort',
        'internal_traffic_policy' => 'setInternalTrafficPolicy',
        'ip_families' => 'setIpFamilies',
        'ip_family_policy' => 'setIpFamilyPolicy',
        'load_balancer_class' => 'setLoadBalancerClass',
        'load_balancer_ip' => 'setLoadBalancerIp',
        'load_balancer_source_ranges' => 'setLoadBalancerSourceRanges',
        'ports' => 'setPorts',
        'publish_not_ready_addresses' => 'setPublishNotReadyAddresses',
        'selector' => 'setSelector',
        'session_affinity' => 'setSessionAffinity',
        'session_affinity_config' => 'setSessionAffinityConfig',
        'traffic_distribution' => 'setTrafficDistribution',
        'type' => 'setType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allocate_load_balancer_node_ports' => 'getAllocateLoadBalancerNodePorts',
        'cluster_ip' => 'getClusterIp',
        'cluster_ips' => 'getClusterIps',
        'external_ips' => 'getExternalIps',
        'external_name' => 'getExternalName',
        'external_traffic_policy' => 'getExternalTrafficPolicy',
        'health_check_node_port' => 'getHealthCheckNodePort',
        'internal_traffic_policy' => 'getInternalTrafficPolicy',
        'ip_families' => 'getIpFamilies',
        'ip_family_policy' => 'getIpFamilyPolicy',
        'load_balancer_class' => 'getLoadBalancerClass',
        'load_balancer_ip' => 'getLoadBalancerIp',
        'load_balancer_source_ranges' => 'getLoadBalancerSourceRanges',
        'ports' => 'getPorts',
        'publish_not_ready_addresses' => 'getPublishNotReadyAddresses',
        'selector' => 'getSelector',
        'session_affinity' => 'getSessionAffinity',
        'session_affinity_config' => 'getSessionAffinityConfig',
        'traffic_distribution' => 'getTrafficDistribution',
        'type' => 'getType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allocate_load_balancer_node_ports', $data ?? [], null);
        $this->setIfExists('cluster_ip', $data ?? [], null);
        $this->setIfExists('cluster_ips', $data ?? [], null);
        $this->setIfExists('external_ips', $data ?? [], null);
        $this->setIfExists('external_name', $data ?? [], null);
        $this->setIfExists('external_traffic_policy', $data ?? [], null);
        $this->setIfExists('health_check_node_port', $data ?? [], null);
        $this->setIfExists('internal_traffic_policy', $data ?? [], null);
        $this->setIfExists('ip_families', $data ?? [], null);
        $this->setIfExists('ip_family_policy', $data ?? [], null);
        $this->setIfExists('load_balancer_class', $data ?? [], null);
        $this->setIfExists('load_balancer_ip', $data ?? [], null);
        $this->setIfExists('load_balancer_source_ranges', $data ?? [], null);
        $this->setIfExists('ports', $data ?? [], null);
        $this->setIfExists('publish_not_ready_addresses', $data ?? [], null);
        $this->setIfExists('selector', $data ?? [], null);
        $this->setIfExists('session_affinity', $data ?? [], null);
        $this->setIfExists('session_affinity_config', $data ?? [], null);
        $this->setIfExists('traffic_distribution', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allocate_load_balancer_node_ports
     *
     * @return bool|null
     */
    public function getAllocateLoadBalancerNodePorts()
    {
        return $this->container['allocate_load_balancer_node_ports'];
    }

    /**
     * Sets allocate_load_balancer_node_ports
     *
     * @param bool|null $allocate_load_balancer_node_ports allocateLoadBalancerNodePorts defines if NodePorts will be automatically allocated for services with type LoadBalancer.  Default is \"true\". It may be set to \"false\" if the cluster load-balancer does not rely on NodePorts.  If the caller requests specific NodePorts (by specifying a value), those requests will be respected, regardless of this field. This field may only be set for services with type LoadBalancer and will be cleared if the type is changed to any other type.
     *
     * @return self
     */
    public function setAllocateLoadBalancerNodePorts($allocate_load_balancer_node_ports)
    {
        if (is_null($allocate_load_balancer_node_ports)) {
            throw new \InvalidArgumentException('non-nullable allocate_load_balancer_node_ports cannot be null');
        }
        $this->container['allocate_load_balancer_node_ports'] = $allocate_load_balancer_node_ports;

        return $this;
    }

    /**
     * Gets cluster_ip
     *
     * @return string|null
     */
    public function getClusterIp()
    {
        return $this->container['cluster_ip'];
    }

    /**
     * Sets cluster_ip
     *
     * @param string|null $cluster_ip clusterIP is the IP address of the service and is usually assigned randomly. If an address is specified manually, is in-range (as per system configuration), and is not in use, it will be allocated to the service; otherwise creation of the service will fail. This field may not be changed through updates unless the type field is also being changed to ExternalName (which requires this field to be blank) or the type field is being changed from ExternalName (in which case this field may optionally be specified, as describe above).  Valid values are \"None\", empty string (\"\"), or a valid IP address. Setting this to \"None\" makes a \"headless service\" (no virtual IP), which is useful when direct endpoint connections are preferred and proxying is not required.  Only applies to types ClusterIP, NodePort, and LoadBalancer. If this field is specified when creating a Service of type ExternalName, creation will fail. This field will be wiped when updating a Service to type ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
     *
     * @return self
     */
    public function setClusterIp($cluster_ip)
    {
        if (is_null($cluster_ip)) {
            throw new \InvalidArgumentException('non-nullable cluster_ip cannot be null');
        }
        $this->container['cluster_ip'] = $cluster_ip;

        return $this;
    }

    /**
     * Gets cluster_ips
     *
     * @return string[]|null
     */
    public function getClusterIps()
    {
        return $this->container['cluster_ips'];
    }

    /**
     * Sets cluster_ips
     *
     * @param string[]|null $cluster_ips ClusterIPs is a list of IP addresses assigned to this service, and are usually assigned randomly.  If an address is specified manually, is in-range (as per system configuration), and is not in use, it will be allocated to the service; otherwise creation of the service will fail. This field may not be changed through updates unless the type field is also being changed to ExternalName (which requires this field to be empty) or the type field is being changed from ExternalName (in which case this field may optionally be specified, as describe above).  Valid values are \"None\", empty string (\"\"), or a valid IP address.  Setting this to \"None\" makes a \"headless service\" (no virtual IP), which is useful when direct endpoint connections are preferred and proxying is not required.  Only applies to types ClusterIP, NodePort, and LoadBalancer. If this field is specified when creating a Service of type ExternalName, creation will fail. This field will be wiped when updating a Service to type ExternalName.  If this field is not specified, it will be initialized from the clusterIP field.  If this field is specified, clients must ensure that clusterIPs[0] and clusterIP have the same value.  This field may hold a maximum of two entries (dual-stack IPs, in either order). These IPs must correspond to the values of the ipFamilies field. Both clusterIPs and ipFamilies are governed by the ipFamilyPolicy field. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
     *
     * @return self
     */
    public function setClusterIps($cluster_ips)
    {
        if (is_null($cluster_ips)) {
            throw new \InvalidArgumentException('non-nullable cluster_ips cannot be null');
        }
        $this->container['cluster_ips'] = $cluster_ips;

        return $this;
    }

    /**
     * Gets external_ips
     *
     * @return string[]|null
     */
    public function getExternalIps()
    {
        return $this->container['external_ips'];
    }

    /**
     * Sets external_ips
     *
     * @param string[]|null $external_ips externalIPs is a list of IP addresses for which nodes in the cluster will also accept traffic for this service.  These IPs are not managed by Kubernetes.  The user is responsible for ensuring that traffic arrives at a node with this IP.  A common example is external load-balancers that are not part of the Kubernetes system.
     *
     * @return self
     */
    public function setExternalIps($external_ips)
    {
        if (is_null($external_ips)) {
            throw new \InvalidArgumentException('non-nullable external_ips cannot be null');
        }
        $this->container['external_ips'] = $external_ips;

        return $this;
    }

    /**
     * Gets external_name
     *
     * @return string|null
     */
    public function getExternalName()
    {
        return $this->container['external_name'];
    }

    /**
     * Sets external_name
     *
     * @param string|null $external_name externalName is the external reference that discovery mechanisms will return as an alias for this service (e.g. a DNS CNAME record). No proxying will be involved.  Must be a lowercase RFC-1123 hostname (https://tools.ietf.org/html/rfc1123) and requires `type` to be \"ExternalName\".
     *
     * @return self
     */
    public function setExternalName($external_name)
    {
        if (is_null($external_name)) {
            throw new \InvalidArgumentException('non-nullable external_name cannot be null');
        }
        $this->container['external_name'] = $external_name;

        return $this;
    }

    /**
     * Gets external_traffic_policy
     *
     * @return string|null
     */
    public function getExternalTrafficPolicy()
    {
        return $this->container['external_traffic_policy'];
    }

    /**
     * Sets external_traffic_policy
     *
     * @param string|null $external_traffic_policy externalTrafficPolicy describes how nodes distribute service traffic they receive on one of the Service's \"externally-facing\" addresses (NodePorts, ExternalIPs, and LoadBalancer IPs). If set to \"Local\", the proxy will configure the service in a way that assumes that external load balancers will take care of balancing the service traffic between nodes, and so each node will deliver traffic only to the node-local endpoints of the service, without masquerading the client source IP. (Traffic mistakenly sent to a node with no endpoints will be dropped.) The default value, \"Cluster\", uses the standard behavior of routing to all endpoints evenly (possibly modified by topology and other features). Note that traffic sent to an External IP or LoadBalancer IP from within the cluster will always get \"Cluster\" semantics, but clients sending to a NodePort from within the cluster may need to take traffic policy into account when picking a node.
     *
     * @return self
     */
    public function setExternalTrafficPolicy($external_traffic_policy)
    {
        if (is_null($external_traffic_policy)) {
            throw new \InvalidArgumentException('non-nullable external_traffic_policy cannot be null');
        }
        $this->container['external_traffic_policy'] = $external_traffic_policy;

        return $this;
    }

    /**
     * Gets health_check_node_port
     *
     * @return int|null
     */
    public function getHealthCheckNodePort()
    {
        return $this->container['health_check_node_port'];
    }

    /**
     * Sets health_check_node_port
     *
     * @param int|null $health_check_node_port healthCheckNodePort specifies the healthcheck nodePort for the service. This only applies when type is set to LoadBalancer and externalTrafficPolicy is set to Local. If a value is specified, is in-range, and is not in use, it will be used.  If not specified, a value will be automatically allocated.  External systems (e.g. load-balancers) can use this port to determine if a given node holds endpoints for this service or not.  If this field is specified when creating a Service which does not need it, creation will fail. This field will be wiped when updating a Service to no longer need it (e.g. changing type). This field cannot be updated once set.
     *
     * @return self
     */
    public function setHealthCheckNodePort($health_check_node_port)
    {
        if (is_null($health_check_node_port)) {
            throw new \InvalidArgumentException('non-nullable health_check_node_port cannot be null');
        }
        $this->container['health_check_node_port'] = $health_check_node_port;

        return $this;
    }

    /**
     * Gets internal_traffic_policy
     *
     * @return string|null
     */
    public function getInternalTrafficPolicy()
    {
        return $this->container['internal_traffic_policy'];
    }

    /**
     * Sets internal_traffic_policy
     *
     * @param string|null $internal_traffic_policy InternalTrafficPolicy describes how nodes distribute service traffic they receive on the ClusterIP. If set to \"Local\", the proxy will assume that pods only want to talk to endpoints of the service on the same node as the pod, dropping the traffic if there are no local endpoints. The default value, \"Cluster\", uses the standard behavior of routing to all endpoints evenly (possibly modified by topology and other features).
     *
     * @return self
     */
    public function setInternalTrafficPolicy($internal_traffic_policy)
    {
        if (is_null($internal_traffic_policy)) {
            throw new \InvalidArgumentException('non-nullable internal_traffic_policy cannot be null');
        }
        $this->container['internal_traffic_policy'] = $internal_traffic_policy;

        return $this;
    }

    /**
     * Gets ip_families
     *
     * @return string[]|null
     */
    public function getIpFamilies()
    {
        return $this->container['ip_families'];
    }

    /**
     * Sets ip_families
     *
     * @param string[]|null $ip_families IPFamilies is a list of IP families (e.g. IPv4, IPv6) assigned to this service. This field is usually assigned automatically based on cluster configuration and the ipFamilyPolicy field. If this field is specified manually, the requested family is available in the cluster, and ipFamilyPolicy allows it, it will be used; otherwise creation of the service will fail. This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service. Valid values are \"IPv4\" and \"IPv6\".  This field only applies to Services of types ClusterIP, NodePort, and LoadBalancer, and does apply to \"headless\" services. This field will be wiped when updating a Service to type ExternalName.  This field may hold a maximum of two entries (dual-stack families, in either order).  These families must correspond to the values of the clusterIPs field, if specified. Both clusterIPs and ipFamilies are governed by the ipFamilyPolicy field.
     *
     * @return self
     */
    public function setIpFamilies($ip_families)
    {
        if (is_null($ip_families)) {
            throw new \InvalidArgumentException('non-nullable ip_families cannot be null');
        }
        $this->container['ip_families'] = $ip_families;

        return $this;
    }

    /**
     * Gets ip_family_policy
     *
     * @return string|null
     */
    public function getIpFamilyPolicy()
    {
        return $this->container['ip_family_policy'];
    }

    /**
     * Sets ip_family_policy
     *
     * @param string|null $ip_family_policy IPFamilyPolicy represents the dual-stack-ness requested or required by this Service. If there is no value provided, then this field will be set to SingleStack. Services can be \"SingleStack\" (a single IP family), \"PreferDualStack\" (two IP families on dual-stack configured clusters or a single IP family on single-stack clusters), or \"RequireDualStack\" (two IP families on dual-stack configured clusters, otherwise fail). The ipFamilies and clusterIPs fields depend on the value of this field. This field will be wiped when updating a service to type ExternalName.
     *
     * @return self
     */
    public function setIpFamilyPolicy($ip_family_policy)
    {
        if (is_null($ip_family_policy)) {
            throw new \InvalidArgumentException('non-nullable ip_family_policy cannot be null');
        }
        $this->container['ip_family_policy'] = $ip_family_policy;

        return $this;
    }

    /**
     * Gets load_balancer_class
     *
     * @return string|null
     */
    public function getLoadBalancerClass()
    {
        return $this->container['load_balancer_class'];
    }

    /**
     * Sets load_balancer_class
     *
     * @param string|null $load_balancer_class loadBalancerClass is the class of the load balancer implementation this Service belongs to. If specified, the value of this field must be a label-style identifier, with an optional prefix, e.g. \"internal-vip\" or \"example.com/internal-vip\". Unprefixed names are reserved for end-users. This field can only be set when the Service type is 'LoadBalancer'. If not set, the default load balancer implementation is used, today this is typically done through the cloud provider integration, but should apply for any default implementation. If set, it is assumed that a load balancer implementation is watching for Services with a matching class. Any default load balancer implementation (e.g. cloud providers) should ignore Services that set this field. This field can only be set when creating or updating a Service to type 'LoadBalancer'. Once set, it can not be changed. This field will be wiped when a service is updated to a non 'LoadBalancer' type.
     *
     * @return self
     */
    public function setLoadBalancerClass($load_balancer_class)
    {
        if (is_null($load_balancer_class)) {
            throw new \InvalidArgumentException('non-nullable load_balancer_class cannot be null');
        }
        $this->container['load_balancer_class'] = $load_balancer_class;

        return $this;
    }

    /**
     * Gets load_balancer_ip
     *
     * @return string|null
     */
    public function getLoadBalancerIp()
    {
        return $this->container['load_balancer_ip'];
    }

    /**
     * Sets load_balancer_ip
     *
     * @param string|null $load_balancer_ip Only applies to Service Type: LoadBalancer. This feature depends on whether the underlying cloud-provider supports specifying the loadBalancerIP when a load balancer is created. This field will be ignored if the cloud-provider does not support the feature. Deprecated: This field was under-specified and its meaning varies across implementations. Using it is non-portable and it may not support dual-stack. Users are encouraged to use implementation-specific annotations when available.
     *
     * @return self
     */
    public function setLoadBalancerIp($load_balancer_ip)
    {
        if (is_null($load_balancer_ip)) {
            throw new \InvalidArgumentException('non-nullable load_balancer_ip cannot be null');
        }
        $this->container['load_balancer_ip'] = $load_balancer_ip;

        return $this;
    }

    /**
     * Gets load_balancer_source_ranges
     *
     * @return string[]|null
     */
    public function getLoadBalancerSourceRanges()
    {
        return $this->container['load_balancer_source_ranges'];
    }

    /**
     * Sets load_balancer_source_ranges
     *
     * @param string[]|null $load_balancer_source_ranges If specified and supported by the platform, this will restrict traffic through the cloud-provider load-balancer will be restricted to the specified client IPs. This field will be ignored if the cloud-provider does not support the feature.\" More info: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
     *
     * @return self
     */
    public function setLoadBalancerSourceRanges($load_balancer_source_ranges)
    {
        if (is_null($load_balancer_source_ranges)) {
            throw new \InvalidArgumentException('non-nullable load_balancer_source_ranges cannot be null');
        }
        $this->container['load_balancer_source_ranges'] = $load_balancer_source_ranges;

        return $this;
    }

    /**
     * Gets ports
     *
     * @return \Kubernetes\Client\Model\V1ServicePort[]|null
     */
    public function getPorts()
    {
        return $this->container['ports'];
    }

    /**
     * Sets ports
     *
     * @param \Kubernetes\Client\Model\V1ServicePort[]|null $ports The list of ports that are exposed by this service. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
     *
     * @return self
     */
    public function setPorts($ports)
    {
        if (is_null($ports)) {
            throw new \InvalidArgumentException('non-nullable ports cannot be null');
        }
        $this->container['ports'] = $ports;

        return $this;
    }

    /**
     * Gets publish_not_ready_addresses
     *
     * @return bool|null
     */
    public function getPublishNotReadyAddresses()
    {
        return $this->container['publish_not_ready_addresses'];
    }

    /**
     * Sets publish_not_ready_addresses
     *
     * @param bool|null $publish_not_ready_addresses publishNotReadyAddresses indicates that any agent which deals with endpoints for this Service should disregard any indications of ready/not-ready. The primary use case for setting this field is for a StatefulSet's Headless Service to propagate SRV DNS records for its Pods for the purpose of peer discovery. The Kubernetes controllers that generate Endpoints and EndpointSlice resources for Services interpret this to mean that all endpoints are considered \"ready\" even if the Pods themselves are not. Agents which consume only Kubernetes generated endpoints through the Endpoints or EndpointSlice resources can safely assume this behavior.
     *
     * @return self
     */
    public function setPublishNotReadyAddresses($publish_not_ready_addresses)
    {
        if (is_null($publish_not_ready_addresses)) {
            throw new \InvalidArgumentException('non-nullable publish_not_ready_addresses cannot be null');
        }
        $this->container['publish_not_ready_addresses'] = $publish_not_ready_addresses;

        return $this;
    }

    /**
     * Gets selector
     *
     * @return array<string,string>|null
     */
    public function getSelector()
    {
        return $this->container['selector'];
    }

    /**
     * Sets selector
     *
     * @param array<string,string>|null $selector Route service traffic to pods with label keys and values matching this selector. If empty or not present, the service is assumed to have an external process managing its endpoints, which Kubernetes will not modify. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/
     *
     * @return self
     */
    public function setSelector($selector)
    {
        if (is_null($selector)) {
            throw new \InvalidArgumentException('non-nullable selector cannot be null');
        }
        $this->container['selector'] = $selector;

        return $this;
    }

    /**
     * Gets session_affinity
     *
     * @return string|null
     */
    public function getSessionAffinity()
    {
        return $this->container['session_affinity'];
    }

    /**
     * Sets session_affinity
     *
     * @param string|null $session_affinity Supports \"ClientIP\" and \"None\". Used to maintain session affinity. Enable client IP based session affinity. Must be ClientIP or None. Defaults to None. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
     *
     * @return self
     */
    public function setSessionAffinity($session_affinity)
    {
        if (is_null($session_affinity)) {
            throw new \InvalidArgumentException('non-nullable session_affinity cannot be null');
        }
        $this->container['session_affinity'] = $session_affinity;

        return $this;
    }

    /**
     * Gets session_affinity_config
     *
     * @return \Kubernetes\Client\Model\V1SessionAffinityConfig|null
     */
    public function getSessionAffinityConfig()
    {
        return $this->container['session_affinity_config'];
    }

    /**
     * Sets session_affinity_config
     *
     * @param \Kubernetes\Client\Model\V1SessionAffinityConfig|null $session_affinity_config session_affinity_config
     *
     * @return self
     */
    public function setSessionAffinityConfig($session_affinity_config)
    {
        if (is_null($session_affinity_config)) {
            throw new \InvalidArgumentException('non-nullable session_affinity_config cannot be null');
        }
        $this->container['session_affinity_config'] = $session_affinity_config;

        return $this;
    }

    /**
     * Gets traffic_distribution
     *
     * @return string|null
     */
    public function getTrafficDistribution()
    {
        return $this->container['traffic_distribution'];
    }

    /**
     * Sets traffic_distribution
     *
     * @param string|null $traffic_distribution TrafficDistribution offers a way to express preferences for how traffic is distributed to Service endpoints. Implementations can use this field as a hint, but are not required to guarantee strict adherence. If the field is not set, the implementation will apply its default routing strategy. If set to \"PreferClose\", implementations should prioritize endpoints that are topologically close (e.g., same zone). This is an alpha field and requires enabling ServiceTrafficDistribution feature.
     *
     * @return self
     */
    public function setTrafficDistribution($traffic_distribution)
    {
        if (is_null($traffic_distribution)) {
            throw new \InvalidArgumentException('non-nullable traffic_distribution cannot be null');
        }
        $this->container['traffic_distribution'] = $traffic_distribution;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer. \"ClusterIP\" allocates a cluster-internal IP address for load-balancing to endpoints. Endpoints are determined by the selector or if that is not specified, by manual construction of an Endpoints object or EndpointSlice objects. If clusterIP is \"None\", no virtual IP is allocated and the endpoints are published as a set of endpoints rather than a virtual IP. \"NodePort\" builds on ClusterIP and allocates a port on every node which routes to the same endpoints as the clusterIP. \"LoadBalancer\" builds on NodePort and creates an external load-balancer (if supported in the current cloud) which routes to the same endpoints as the clusterIP. \"ExternalName\" aliases this service to the specified externalName. Several other fields do not apply to ExternalName services. More info: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


