<?php
/**
 * V1WindowsSecurityContextOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kubernetes\Client\Model;

use \ArrayAccess;
use \Kubernetes\Client\ObjectSerializer;

/**
 * V1WindowsSecurityContextOptions Class Doc Comment
 *
 * @category Class
 * @description WindowsSecurityContextOptions contain Windows-specific options and credentials.
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1WindowsSecurityContextOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1.WindowsSecurityContextOptions';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'gmsa_credential_spec' => 'string',
        'gmsa_credential_spec_name' => 'string',
        'host_process' => 'bool',
        'run_as_user_name' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'gmsa_credential_spec' => null,
        'gmsa_credential_spec_name' => null,
        'host_process' => null,
        'run_as_user_name' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'gmsa_credential_spec' => false,
        'gmsa_credential_spec_name' => false,
        'host_process' => false,
        'run_as_user_name' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'gmsa_credential_spec' => 'gmsaCredentialSpec',
        'gmsa_credential_spec_name' => 'gmsaCredentialSpecName',
        'host_process' => 'hostProcess',
        'run_as_user_name' => 'runAsUserName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'gmsa_credential_spec' => 'setGmsaCredentialSpec',
        'gmsa_credential_spec_name' => 'setGmsaCredentialSpecName',
        'host_process' => 'setHostProcess',
        'run_as_user_name' => 'setRunAsUserName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'gmsa_credential_spec' => 'getGmsaCredentialSpec',
        'gmsa_credential_spec_name' => 'getGmsaCredentialSpecName',
        'host_process' => 'getHostProcess',
        'run_as_user_name' => 'getRunAsUserName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('gmsa_credential_spec', $data ?? [], null);
        $this->setIfExists('gmsa_credential_spec_name', $data ?? [], null);
        $this->setIfExists('host_process', $data ?? [], null);
        $this->setIfExists('run_as_user_name', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets gmsa_credential_spec
     *
     * @return string|null
     */
    public function getGmsaCredentialSpec()
    {
        return $this->container['gmsa_credential_spec'];
    }

    /**
     * Sets gmsa_credential_spec
     *
     * @param string|null $gmsa_credential_spec GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
     *
     * @return self
     */
    public function setGmsaCredentialSpec($gmsa_credential_spec)
    {
        if (is_null($gmsa_credential_spec)) {
            throw new \InvalidArgumentException('non-nullable gmsa_credential_spec cannot be null');
        }
        $this->container['gmsa_credential_spec'] = $gmsa_credential_spec;

        return $this;
    }

    /**
     * Gets gmsa_credential_spec_name
     *
     * @return string|null
     */
    public function getGmsaCredentialSpecName()
    {
        return $this->container['gmsa_credential_spec_name'];
    }

    /**
     * Sets gmsa_credential_spec_name
     *
     * @param string|null $gmsa_credential_spec_name GMSACredentialSpecName is the name of the GMSA credential spec to use.
     *
     * @return self
     */
    public function setGmsaCredentialSpecName($gmsa_credential_spec_name)
    {
        if (is_null($gmsa_credential_spec_name)) {
            throw new \InvalidArgumentException('non-nullable gmsa_credential_spec_name cannot be null');
        }
        $this->container['gmsa_credential_spec_name'] = $gmsa_credential_spec_name;

        return $this;
    }

    /**
     * Gets host_process
     *
     * @return bool|null
     */
    public function getHostProcess()
    {
        return $this->container['host_process'];
    }

    /**
     * Sets host_process
     *
     * @param bool|null $host_process HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
     *
     * @return self
     */
    public function setHostProcess($host_process)
    {
        if (is_null($host_process)) {
            throw new \InvalidArgumentException('non-nullable host_process cannot be null');
        }
        $this->container['host_process'] = $host_process;

        return $this;
    }

    /**
     * Gets run_as_user_name
     *
     * @return string|null
     */
    public function getRunAsUserName()
    {
        return $this->container['run_as_user_name'];
    }

    /**
     * Sets run_as_user_name
     *
     * @param string|null $run_as_user_name The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
     *
     * @return self
     */
    public function setRunAsUserName($run_as_user_name)
    {
        if (is_null($run_as_user_name)) {
            throw new \InvalidArgumentException('non-nullable run_as_user_name cannot be null');
        }
        $this->container['run_as_user_name'] = $run_as_user_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


