<?php
/**
 * V1OverheadTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Kubernetes\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1OverheadTest Class Doc Comment
 *
 * @category    Class
 * @description Overhead structure represents the resource overhead associated with running a pod.
 * @package     Kubernetes\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1OverheadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1Overhead"
     */
    public function testV1Overhead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pod_fixed"
     */
    public function testPropertyPodFixed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
