<?php
/**
 * V1PodTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Kubernetes\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1PodTest Class Doc Comment
 *
 * @category    Class
 * @description Pod is a collection of containers that can run on a host. This resource is created by clients and scheduled onto hosts.
 * @package     Kubernetes\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1PodTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1Pod"
     */
    public function testV1Pod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "api_version"
     */
    public function testPropertyApiVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spec"
     */
    public function testPropertySpec()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
