<?php
/**
 * V1ScaleIOPersistentVolumeSourceTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Kubernetes\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1ScaleIOPersistentVolumeSourceTest Class Doc Comment
 *
 * @category    Class
 * @description ScaleIOPersistentVolumeSource represents a persistent ScaleIO volume
 * @package     Kubernetes\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1ScaleIOPersistentVolumeSourceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1ScaleIOPersistentVolumeSource"
     */
    public function testV1ScaleIOPersistentVolumeSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fs_type"
     */
    public function testPropertyFsType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gateway"
     */
    public function testPropertyGateway()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "protection_domain"
     */
    public function testPropertyProtectionDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "read_only"
     */
    public function testPropertyReadOnly()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "secret_ref"
     */
    public function testPropertySecretRef()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssl_enabled"
     */
    public function testPropertySslEnabled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "storage_mode"
     */
    public function testPropertyStorageMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "storage_pool"
     */
    public function testPropertyStoragePool()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "system"
     */
    public function testPropertySystem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "volume_name"
     */
    public function testPropertyVolumeName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
