<?php
/**
 * AppsV1ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.31
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kubernetes\Client\Test\Api;

use \Kubernetes\Client\Configuration;
use \Kubernetes\Client\ApiException;
use \Kubernetes\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppsV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppsV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createNamespacedControllerRevision
     *
     * .
     *
     */
    public function testCreateNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNamespacedDaemonSet
     *
     * .
     *
     */
    public function testCreateNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNamespacedDeployment
     *
     * .
     *
     */
    public function testCreateNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNamespacedReplicaSet
     *
     * .
     *
     */
    public function testCreateNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNamespacedStatefulSet
     *
     * .
     *
     */
    public function testCreateNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedControllerRevision
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedDaemonSet
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedDeployment
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedReplicaSet
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedStatefulSet
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedControllerRevision
     *
     * .
     *
     */
    public function testDeleteNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedDaemonSet
     *
     * .
     *
     */
    public function testDeleteNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedDeployment
     *
     * .
     *
     */
    public function testDeleteNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedReplicaSet
     *
     * .
     *
     */
    public function testDeleteNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedStatefulSet
     *
     * .
     *
     */
    public function testDeleteNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listControllerRevisionForAllNamespaces
     *
     * .
     *
     */
    public function testListControllerRevisionForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDaemonSetForAllNamespaces
     *
     * .
     *
     */
    public function testListDaemonSetForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDeploymentForAllNamespaces
     *
     * .
     *
     */
    public function testListDeploymentForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedControllerRevision
     *
     * .
     *
     */
    public function testListNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedDaemonSet
     *
     * .
     *
     */
    public function testListNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedDeployment
     *
     * .
     *
     */
    public function testListNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedReplicaSet
     *
     * .
     *
     */
    public function testListNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedStatefulSet
     *
     * .
     *
     */
    public function testListNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listReplicaSetForAllNamespaces
     *
     * .
     *
     */
    public function testListReplicaSetForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listStatefulSetForAllNamespaces
     *
     * .
     *
     */
    public function testListStatefulSetForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedControllerRevision
     *
     * .
     *
     */
    public function testPatchNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedDaemonSet
     *
     * .
     *
     */
    public function testPatchNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedDaemonSetStatus
     *
     * .
     *
     */
    public function testPatchNamespacedDaemonSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedDeployment
     *
     * .
     *
     */
    public function testPatchNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedDeploymentScale
     *
     * .
     *
     */
    public function testPatchNamespacedDeploymentScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedDeploymentStatus
     *
     * .
     *
     */
    public function testPatchNamespacedDeploymentStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedReplicaSet
     *
     * .
     *
     */
    public function testPatchNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedReplicaSetScale
     *
     * .
     *
     */
    public function testPatchNamespacedReplicaSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedReplicaSetStatus
     *
     * .
     *
     */
    public function testPatchNamespacedReplicaSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedStatefulSet
     *
     * .
     *
     */
    public function testPatchNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedStatefulSetScale
     *
     * .
     *
     */
    public function testPatchNamespacedStatefulSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedStatefulSetStatus
     *
     * .
     *
     */
    public function testPatchNamespacedStatefulSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedControllerRevision
     *
     * .
     *
     */
    public function testReadNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedDaemonSet
     *
     * .
     *
     */
    public function testReadNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedDaemonSetStatus
     *
     * .
     *
     */
    public function testReadNamespacedDaemonSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedDeployment
     *
     * .
     *
     */
    public function testReadNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedDeploymentScale
     *
     * .
     *
     */
    public function testReadNamespacedDeploymentScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedDeploymentStatus
     *
     * .
     *
     */
    public function testReadNamespacedDeploymentStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedReplicaSet
     *
     * .
     *
     */
    public function testReadNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedReplicaSetScale
     *
     * .
     *
     */
    public function testReadNamespacedReplicaSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedReplicaSetStatus
     *
     * .
     *
     */
    public function testReadNamespacedReplicaSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedStatefulSet
     *
     * .
     *
     */
    public function testReadNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedStatefulSetScale
     *
     * .
     *
     */
    public function testReadNamespacedStatefulSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedStatefulSetStatus
     *
     * .
     *
     */
    public function testReadNamespacedStatefulSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedControllerRevision
     *
     * .
     *
     */
    public function testReplaceNamespacedControllerRevision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedDaemonSet
     *
     * .
     *
     */
    public function testReplaceNamespacedDaemonSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedDaemonSetStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedDaemonSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedDeployment
     *
     * .
     *
     */
    public function testReplaceNamespacedDeployment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedDeploymentScale
     *
     * .
     *
     */
    public function testReplaceNamespacedDeploymentScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedDeploymentStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedDeploymentStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedReplicaSet
     *
     * .
     *
     */
    public function testReplaceNamespacedReplicaSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedReplicaSetScale
     *
     * .
     *
     */
    public function testReplaceNamespacedReplicaSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedReplicaSetStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedReplicaSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedStatefulSet
     *
     * .
     *
     */
    public function testReplaceNamespacedStatefulSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedStatefulSetScale
     *
     * .
     *
     */
    public function testReplaceNamespacedStatefulSetScale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedStatefulSetStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedStatefulSetStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
