<?php
/**
 * LifecycleV1alpha1ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kubernetes\Client\Test\Api;

use \Kubernetes\Client\Configuration;
use \Kubernetes\Client\ApiException;
use \Kubernetes\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LifecycleV1alpha1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LifecycleV1alpha1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createNamespacedEviction
     *
     * .
     *
     */
    public function testCreateNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testCreateNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedEviction
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testDeleteCollectionNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedEviction
     *
     * .
     *
     */
    public function testDeleteNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testDeleteNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEvictionForAllNamespaces
     *
     * .
     *
     */
    public function testListEvictionForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEvictionRequestForAllNamespaces
     *
     * .
     *
     */
    public function testListEvictionRequestForAllNamespaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedEviction
     *
     * .
     *
     */
    public function testListNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testListNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedEviction
     *
     * .
     *
     */
    public function testPatchNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testPatchNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedEvictionRequestStatus
     *
     * .
     *
     */
    public function testPatchNamespacedEvictionRequestStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNamespacedEvictionStatus
     *
     * .
     *
     */
    public function testPatchNamespacedEvictionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedEviction
     *
     * .
     *
     */
    public function testReadNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testReadNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedEvictionRequestStatus
     *
     * .
     *
     */
    public function testReadNamespacedEvictionRequestStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readNamespacedEvictionStatus
     *
     * .
     *
     */
    public function testReadNamespacedEvictionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedEviction
     *
     * .
     *
     */
    public function testReplaceNamespacedEviction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedEvictionRequest
     *
     * .
     *
     */
    public function testReplaceNamespacedEvictionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedEvictionRequestStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedEvictionRequestStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceNamespacedEvictionStatus
     *
     * .
     *
     */
    public function testReplaceNamespacedEvictionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
