<?php
/**
 * StoragemigrationV1ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.37
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kubernetes\Client\Test\Api;

use \Kubernetes\Client\Configuration;
use \Kubernetes\Client\ApiException;
use \Kubernetes\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StoragemigrationV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kubernetes\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StoragemigrationV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createStorageVersionMigration
     *
     * .
     *
     */
    public function testCreateStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCollectionStorageVersionMigration
     *
     * .
     *
     */
    public function testDeleteCollectionStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteStorageVersionMigration
     *
     * .
     *
     */
    public function testDeleteStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAPIResources
     *
     * .
     *
     */
    public function testGetAPIResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listStorageVersionMigration
     *
     * .
     *
     */
    public function testListStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchStorageVersionMigration
     *
     * .
     *
     */
    public function testPatchStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchStorageVersionMigrationStatus
     *
     * .
     *
     */
    public function testPatchStorageVersionMigrationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readStorageVersionMigration
     *
     * .
     *
     */
    public function testReadStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readStorageVersionMigrationStatus
     *
     * .
     *
     */
    public function testReadStorageVersionMigrationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceStorageVersionMigration
     *
     * .
     *
     */
    public function testReplaceStorageVersionMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceStorageVersionMigrationStatus
     *
     * .
     *
     */
    public function testReplaceStorageVersionMigrationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
